# Generated by Django 5.1.3 on 2024-12-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='revieww',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
